services:
  postgres:
    image: postgres:17
    container_name: postgres_contratacion_db
    restart: unless-stopped
    ports:
      - '127.0.0.1:5436:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bd_sistema_contratacion
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
      target: development
    container_name: backend_contratacion_app
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./server/:/app
      - node_modules_backend:/app/node_modules
      - ./uploads:/app/uploads
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/bd_coboce
      NODE_ENV: development
      JWT_SECRET: tu_secreto_jwt_aqui
      JWT_EXPIRES_IN: 1d
      DB_SSL: false
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: bd_sistema_contratacion
      DB_HOST: postgres
      DB_PORT: 5432
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 465
      MAIL_SECURE: true
      MAIL_USER: papicrack70@gmail.com
      MAIL_PASSWORD: 'uawcgehoxcuxrwcn'

    depends_on:
      - postgres

  frontend:
    build:
      context: ./client
      target: development
    container_name: frontend_contratacion_app
    restart: unless-stopped
    ports:
      - '8080:5173'
    volumes:
      - ./client/:/app
      - node_modules_frontend:/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000/api
    depends_on:
      - backend

volumes:
  postgres_data:
  node_modules_backend:
  node_modules_frontend:
